// This enum was generated by Dialoguer
//	Do not modify this file, it will be overwritten by Dialoguer.
public enum DialoguerDialogues{
	My_First_Dialogue_Tree = 0,
	My_Second_Dialogue_Tree = 1,
	Stat1 = 2,
	Stat2 = 3,
	Stat3 = 4,
	Returning = 5,
}
